services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MyDatabase;User Id=sa;Password=StrongPassword123!
    networks:
      - app-network

networks:
  app-network:
    driver: bridge



